//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Integrity.DatabaseBuilder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetNuke.Integrity.DatabaseBuilder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only set built database once.
        /// </summary>
        internal static string Error_CanOnlySetBuiltDbOnce {
            get {
                return ResourceManager.GetString("Error_CanOnlySetBuiltDbOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to create the database.
        /// </summary>
        internal static string Error_ErrorCreatingDatabase {
            get {
                return ResourceManager.GetString("Error_ErrorCreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided certificate does not include a private key.
        /// </summary>
        internal static string Error_NoPrivateKey {
            get {
                return ResourceManager.GetString("Error_NoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist: {0}.
        /// </summary>
        internal static string Error_RootFolderDoesNotExist {
            get {
                return ResourceManager.GetString("Error_RootFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering directory {0}.
        /// </summary>
        internal static string Message_EnteringDirectory {
            get {
                return ResourceManager.GetString("Message_EnteringDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} occurred{1}: {2}.
        /// </summary>
        internal static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  while signing file &apos;{0}&apos;.
        /// </summary>
        internal static string Message_ErrorFileReference {
            get {
                return ResourceManager.GetString("Message_ErrorFileReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error.
        /// </summary>
        internal static string Message_ErrorPrefix {
            get {
                return ResourceManager.GetString("Message_ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting directory {0}.
        /// </summary>
        internal static string Message_ExitingDirectory {
            get {
                return ResourceManager.GetString("Message_ExitingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string Message_Failed {
            get {
                return ResourceManager.GetString("Message_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0}: {1} errors, {2} warnings.
        /// </summary>
        internal static string Message_FinishedBuilding {
            get {
                return ResourceManager.GetString("Message_FinishedBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file {0}... .
        /// </summary>
        internal static string Message_ProcessingFile {
            get {
                return ResourceManager.GetString("Message_ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping file {0}.
        /// </summary>
        internal static string Message_SkippingFile {
            get {
                return ResourceManager.GetString("Message_SkippingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building File Integrity Database for directory: {0}.
        /// </summary>
        internal static string Message_StartBuilding {
            get {
                return ResourceManager.GetString("Message_StartBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to succeeded.
        /// </summary>
        internal static string Message_Succeeded {
            get {
                return ResourceManager.GetString("Message_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A warning.
        /// </summary>
        internal static string Message_WarningPrefix {
            get {
                return ResourceManager.GetString("Message_WarningPrefix", resourceCulture);
            }
        }
    }
}
