//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetNuke.Integrity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetNuke.Integrity.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified certificate does not include a private key.
        /// </summary>
        internal static string Error_CertificateHasNoPrivateKey {
            get {
                return ResourceManager.GetString("Error_CertificateHasNoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is not trusted by a trusted file issuer.
        /// </summary>
        internal static string Error_CertificateNotTrustedAsFileIssuer {
            get {
                return ResourceManager.GetString("Error_CertificateNotTrustedAsFileIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate is not trusted by a root certificate authority.
        /// </summary>
        internal static string Error_CertificateNotTrustedByRoot {
            get {
                return ResourceManager.GetString("Error_CertificateNotTrustedByRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate&apos;s private key is of an unsupported format: {0}.
        /// </summary>
        internal static string Error_CertificatePrivateKeyNotSupported {
            get {
                return ResourceManager.GetString("Error_CertificatePrivateKeyNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is read-only.
        /// </summary>
        internal static string Error_DatabaseIsReadOnly {
            get {
                return ResourceManager.GetString("Error_DatabaseIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred validating the database file against the xml schema.
        /// </summary>
        internal static string Error_ErrorValidatingSchema {
            get {
                return ResourceManager.GetString("Error_ErrorValidatingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not a File Integrity Database file.
        /// </summary>
        internal static string Error_FileIsNotDatabase {
            get {
                return ResourceManager.GetString("Error_FileIsNotDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash algorithm &apos;{0}&apos; is not supported.
        /// </summary>
        internal static string Error_HashAlgorithmNotSupported {
            get {
                return ResourceManager.GetString("Error_HashAlgorithmNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database file.
        /// </summary>
        internal static string Error_InvalidDatabaseFile {
            get {
                return ResourceManager.GetString("Error_InvalidDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O error loading database.
        /// </summary>
        internal static string Error_IOErrorLoadingDatabase {
            get {
                return ResourceManager.GetString("Error_IOErrorLoadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Integrity Database does not contain an embedded certificate and no certificate was provided.
        /// </summary>
        internal static string Error_NoEmbeddedCertificate {
            get {
                return ResourceManager.GetString("Error_NoEmbeddedCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security error loading database.
        /// </summary>
        internal static string Error_SecurityErrorLoadingDatabase {
            get {
                return ResourceManager.GetString("Error_SecurityErrorLoadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The signature could not be verified.
        /// </summary>
        internal static string Error_SignatureCouldNotBeVerified {
            get {
                return ResourceManager.GetString("Error_SignatureCouldNotBeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature generation failed.
        /// </summary>
        internal static string Error_SignatureGenerationFailed {
            get {
                return ResourceManager.GetString("Error_SignatureGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature verification failed.
        /// </summary>
        internal static string Error_SignatureVerificationFailed {
            get {
                return ResourceManager.GetString("Error_SignatureVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} parameter is a null reference or an empty string.
        /// </summary>
        internal static string Error_StringArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_StringArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access error loading database.
        /// </summary>
        internal static string Error_UnauthorizedAccessErrorLoadingDatabase {
            get {
                return ResourceManager.GetString("Error_UnauthorizedAccessErrorLoadingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml parsing error loading database.
        /// </summary>
        internal static string Error_XmlErrorLoadingDatabase {
            get {
                return ResourceManager.GetString("Error_XmlErrorLoadingDatabase", resourceCulture);
            }
        }
    }
}
