'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Html

    Partial Public Class EditHtml

        '''<summary>
        '''dshMaster control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshMaster As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblMaster control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblMaster As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''placeMasterContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents placeMasterContent As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dshCurrentContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshCurrentContent As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblEdit As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''txtContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContent As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''rowSubmittedContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowSubmittedContent As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''Div1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litCurrentContentPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCurrentContentPreview As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rowCurrentVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowCurrentVersion As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plCurrentWorkVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCurrentWorkVersion As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblCurrentVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentVersion As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCurrentWorkflowInUse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCurrentWorkflowInUse As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblCurrentWorkflowInUse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentWorkflowInUse As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowCurrentWorkflowState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowCurrentWorkflowState As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plCurrentWorkflowState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCurrentWorkflowState As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblCurrentWorkflowState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentWorkflowState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPublish As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plActionOnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plActionOnSave As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkPublish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPublish As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSave As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPreview As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''dshPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPreview As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPreview As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''rowPreviewVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPreviewVersion As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPreviewVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPreviewVersion As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblPreviewVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreviewVersion As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowPreviewWorlflow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPreviewWorlflow As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPreviewWorkflowInUse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPreviewWorkflowInUse As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblPreviewWorkflowInUse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreviewWorkflowInUse As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rowPreviewWorkflowState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowPreviewWorkflowState As Global.System.Web.UI.HtmlControls.HtmlTableRow

        '''<summary>
        '''plPreviewWorkflowState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPreviewWorkflowState As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblPreviewWorkflowState control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreviewWorkflowState As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Div2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''litPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPreview As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''dshHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshHistory As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblHistory As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''grdLog control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdLog As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''dshVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshVersions As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblVersions As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plMaxVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxVersions As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblMaxVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMaxVersions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdVersions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdVersions As Global.DotNetNuke.Web.UI.WebControls.DnnGrid
    End Class
End Namespace
