//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DotNetNuke.Modules.Messaging.Views
{

	public partial class MessageList
	{

		///<summary>
		///titleLabel control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>

		protected global::System.Web.UI.WebControls.Label titleLabel;
		private global::DotNetNuke.Web.UI.WebControls.DnnGrid withEventsField_messagesGrid;
		///<summary>
		///messagesGrid control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::DotNetNuke.Web.UI.WebControls.DnnGrid messagesGrid
		{
			get { return withEventsField_messagesGrid; }
			set
			{
				if (withEventsField_messagesGrid != null)
				{
					withEventsField_messagesGrid.ItemDataBound -= messagesGrid_ItemDataBound;
					withEventsField_messagesGrid.NeedDataSource -= messagesGrid_NeedDataSource;
				}
				withEventsField_messagesGrid = value;
				if (withEventsField_messagesGrid != null)
				{
					withEventsField_messagesGrid.ItemDataBound += messagesGrid_ItemDataBound;
					withEventsField_messagesGrid.NeedDataSource += messagesGrid_NeedDataSource;
				}
			}

		}
		private global::System.Web.UI.WebControls.Button withEventsField_addMessageButton;
		///<summary>
		///addMessageButton control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.Button addMessageButton
		{
			get { return withEventsField_addMessageButton; }
			set
			{
				if (withEventsField_addMessageButton != null)
				{
					withEventsField_addMessageButton.Click -= addMessageButton_Click;
				}
				withEventsField_addMessageButton = value;
				if (withEventsField_addMessageButton != null)
				{
					withEventsField_addMessageButton.Click += addMessageButton_Click;
				}
			}

		}
		private global::System.Web.UI.WebControls.LinkButton withEventsField_markAsRead;
		///<summary>
		///markAsRead control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.LinkButton markAsRead
		{
			get { return withEventsField_markAsRead; }
			set
			{
				if (withEventsField_markAsRead != null)
				{
					withEventsField_markAsRead.Click -= markAsRead_Click;
				}
				withEventsField_markAsRead = value;
				if (withEventsField_markAsRead != null)
				{
					withEventsField_markAsRead.Click += markAsRead_Click;
				}
			}

		}
		private global::System.Web.UI.WebControls.LinkButton withEventsField_markAsUnread;
		///<summary>
		///markAsUnread control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.LinkButton markAsUnread
		{
			get { return withEventsField_markAsUnread; }
			set
			{
				if (withEventsField_markAsUnread != null)
				{
					withEventsField_markAsUnread.Click -= markAsUnread_Click;
				}
				withEventsField_markAsUnread = value;
				if (withEventsField_markAsUnread != null)
				{
					withEventsField_markAsUnread.Click += markAsUnread_Click;
				}
			}

		}
		private global::System.Web.UI.WebControls.LinkButton withEventsField_delete;
		///<summary>
		///delete control.
		///</summary>
		///<remarks>
		///Auto-generated field.
		///To modify move field declaration from designer file to code-behind file.
		///</remarks>
		protected global::System.Web.UI.WebControls.LinkButton delete
		{
			get { return withEventsField_delete; }
			set
			{
				if (withEventsField_delete != null)
				{
					withEventsField_delete.Click -= delete_Click;
				}
				withEventsField_delete = value;
				if (withEventsField_delete != null)
				{
					withEventsField_delete.Click += delete_Click;
				}
			}
		}
	}
}
