// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DotNetNuke.Website.Specs.Framework
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Online Help")]
    public partial class OnlineHelpFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "OnlineHelp.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Online Help", "In order to display a link to the Online Help\r\nAs an Administrator\r\nI want to be " +
                    "shown the correct URL in the module menu", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Link to Url Online Help URL Field when Help URL Field is populated")]
        [NUnit.Framework.CategoryAttribute("MustBeDefaultAdminCredentials")]
        [NUnit.Framework.CategoryAttribute("MustHaveHelpUrlFilledOutForHtmlModule")]
        public virtual void LinkToUrlOnlineHelpURLFieldWhenHelpURLFieldIsPopulated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Link to Url Online Help URL Field when Help URL Field is populated", new string[] {
                        "MustBeDefaultAdminCredentials",
                        "MustHaveHelpUrlFilledOutForHtmlModule"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am on the site home page");
#line 10
 testRunner.And("I have logged in as the host");
#line 11
 testRunner.And("I have cleared the dotnetnuke cache");
#line 12
 testRunner.When("I click the Module 0 Online Help");
#line 13
 testRunner.Then("I should go to the site hive.dotnetnuke.com");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Link to Url Online Help URL Field when Help URL Field is empty")]
        [NUnit.Framework.CategoryAttribute("MustBeDefaultAdminCredentials")]
        [NUnit.Framework.CategoryAttribute("MustHaveEmptyHelpUrlForHtmlModule")]
        public virtual void LinkToUrlOnlineHelpURLFieldWhenHelpURLFieldIsEmpty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Link to Url Online Help URL Field when Help URL Field is empty", new string[] {
                        "MustBeDefaultAdminCredentials",
                        "MustHaveEmptyHelpUrlForHtmlModule"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I am on the site home page");
#line 19
 testRunner.And("I have logged in as the host");
#line 20
 testRunner.And("I have cleared the dotnetnuke cache");
#line 21
 testRunner.When("I click the Module 0 Online Help");
#line 22
 testRunner.Then("I should go to the site hive.dotnetnuke.com");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
